version: 2

models:
    - name: Candidate_Decisions
      description: "A model for candidate admissions decisions"
      columns:
          - name: Date_Processed
            description: "Date the admissions decision was processed"
            tests:
                - not_null
          - name: Decision_Date
            description: "Date the admissions decision was made"
            tests:
                - not_null
          - name: School_Decision
            description: "The school's decision on the candidate"
            tests:
                - not_null
          - name: Candidate_Decision
            description: "The candidate's enrollment decision"
            tests:
                - not_null
    - name: Candidate_Information
      description: "A model for candidate admissions decisions"
      columns:
          - name: First_Name
            description: "First name"
            tests:
                - not_null
          - name: Last_Name
            description: "Last name"
            tests:
                - not_null
          - name: Entering_Grade
            description: "The grade the student is apply for"
            tests:
                - not_null
